Shared = {}

local StringCharset = {}
local NumberCharset = {}

for i = 48,  57 do table.insert(NumberCharset, string.char(i)) end
for i = 65,  90 do table.insert(StringCharset, string.char(i)) end
for i = 97, 122 do table.insert(StringCharset, string.char(i)) end

Shared.RandomStr = function(Length)
	if Length > 0 then
		return Shared.RandomStr(Length - 1)..StringCharset[math.random(1, #StringCharset)]
	else
		return ''
	end
end

Shared.RandomInt = function(Length)
	if Length > 0 then
		return Shared.RandomInt(Length - 1)..NumberCharset[math.random(1, #NumberCharset)]
	else
		return ''
	end
end

Shared.Tax = {
    ['Property'] = 15, -- +15% of the price
    ['Vehicle'] = 49, -- +49% of the price
    ['Goods'] = 15, -- +15% of the price
    ['Clothes'] = 15, -- +15% of the prices,
    ['Gas'] = 17, -- +17% of the price
}

Shared.Groups = {
    ['user'] = 'User',
    ['admin'] = 'Admin',
    ['god'] = 'God'
}

Shared.Cryptos = {
    ['shungite'] = {
        ['CryptoId'] = 2,
        ['Icon'] = '<i class="fas fa-caret-square-up"></i>',
        ['Label'] = 'Shungite',
        ['Name'] = 'shungite',
        ['Short'] = 'sge',
        ['Worth'] = 2.00,
        ['Purcashable'] = true,
        ['Exchangable'] = true,
    },
    ['guinea'] = {
        ['CryptoId'] = 1,
        ['Icon'] = '<i class="fas fa-horse-head"></i>',
        ['Label'] = 'Guinea',
        ['Name'] = 'guinea',
        ['Short'] = 'gne',
        ['Worth'] = 2.00,
        ['Purcashable'] = true,
        ['Exchangable'] = true,
    },
}

Shared.Jobs = {
    ['unemployed'] = {
        Name = 'unemployed',
        Label = 'Unemployed',
        Salary = 10,
        Duty = false,
        Student = false,
        HighCommand = false
    },
    ['police'] = {
        Name = 'police',
        Label = 'Police',
        Salary = 145,
        Duty = false,
        Callsign = 'XXX',
        Student = false,
        Department = 'LSPD',
        HighCommand = false
    },
    ['ems'] = {
        Name = 'ems',
        Label = 'EMS',
        Salary = 145,
        Duty = false,
        Callsign = 'XXX',
        Student = false,
        HighCommand = false
    },
    ['judge'] = {
        Name = 'judge',
        Label = 'Judge',
        Salary = 200,
        Duty = false,
        Student = false,
        HighCommand = false,
    },
    ['lawyer'] = {
        Name = 'lawyer',
        Label = 'Lawyer',
        Salary = 50,
        Duty = false,
    },
    ['prosecutor'] = {
        Name = 'prosecutor',
        Label = 'Prosecutor',
        Salary = 50,
        Duty = false,
    },
    ['realestate'] = {
        Name = 'realestate',
        Label = 'Real Estate',
        Salary = 50,
        Duty = false,
    },
}

Shared.JobDepartments = {
    ['police'] = {'BCSO', 'LSPD', 'SASP'}
}

Shared.VehicleMods = {
    ['ModSpoilers'] = 0,
    ['ModFrontBumper'] = 1,
    ['ModRearBumper'] = 2,
    ['ModSideSkirt'] = 3,
    ['ModExhaust'] = 4,
    ['ModFrame'] = 5,
    ['ModGrille'] = 6,
    ['ModHood'] = 7,
    ['ModFender'] = 8,
    ['ModRightFender'] = 9,
    ['ModRoof'] = 10,
    ['ModEngine'] = 11,
    ['ModBrakes'] = 12,
    ['ModTransmission'] = 13,
    ['ModHorns'] = 14,
    ['ModSuspension'] = 15,
    ['ModArmor'] = 16,
    ['ModTurbo'] = 18,
    ['ModXenon'] = 22,
    ['ModFrontWheels'] = 23,
    ['ModBackWheels'] = 24,
    ['ModPlateHolder'] = 25,
    ['ModVanityPlate'] = 26,
    ['ModTrimA'] = 27,
    ['ModOrnaments'] = 28,
    ['ModDashboard'] = 29,
    ['ModDial'] = 30,
    ['ModDoorSpeaker'] = 31,
    ['ModSeats'] = 32,
    ['ModSteeringWheel'] = 33,
    ['ModShifterLeavers'] = 34,
    ['ModAPlate'] = 35,
    ['ModSpeakers'] = 36,
    ['ModTrunk'] = 37,
    ['ModHydrolic'] = 38,
    ['ModEngineBlock'] = 39,
    ['ModAirFilter'] = 40,
    ['ModStruts'] = 41,
    ['ModArchCover'] = 42,
    ['ModAerials'] = 43,
    ['ModTrimB'] = 44,
    ['ModTank'] = 45,
    ['ModWindows'] = 46,
    ['ModLivery'] = 48,
}

Shared.Weapons = {
    [GetHashKey('weapon_taser')] = {
        ['WeaponID'] = 'weapon_taser',  
        ['AmmoType'] = '',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 1,
    },
    [GetHashKey('weapon_paintball')] = {
        ['WeaponID'] = 'weapon_paintball',  
        ['AmmoType'] = 'AMMO_PAINTBALL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 200,
    },
    [GetHashKey('weapon_beretta')] = {
        ['WeaponID'] = 'weapon_beretta',  
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_colt')] = {
        ['WeaponID'] = 'weapon_colt',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_glock')] = {
        ['WeaponID'] = 'weapon_glock',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_glock19gen4')] = {
        ['WeaponID'] = 'weapon_glock19gen4',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_waltherp99')] = {
        ['WeaponID'] = 'weapon_waltherp99',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 100,
    },
    [GetHashKey('weapon_glock18c')] = {
        ['WeaponID'] = 'weapon_glock18c',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_browning')] = {
        ['WeaponID'] = 'weapon_browning',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_python')] = {
        ['WeaponID'] = 'weapon_python',   
        ['AmmoType'] = 'AMMO_REVOLVER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 24,
    },
    [GetHashKey('weapon_diamond')] = {
        ['WeaponID'] = 'weapon_diamond',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_heavypistol')] = {
        ['WeaponID'] = 'weapon_heavypistol',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_appistol')] = {
        ['WeaponID'] = 'weapon_appistol',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_mac10')] = {
        ['WeaponID'] = 'weapon_mac10',  
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_uzi')] = {
        ['WeaponID'] = 'weapon_uzi',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_mp5sdfm')] = {
        ['WeaponID'] = 'weapon_mp5sdfm',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_draco')] = {
        ['WeaponID'] = 'weapon_draco',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_mpx')] = {
        ['WeaponID'] = 'weapon_mpx',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_m4')] = {
        ['WeaponID'] = 'weapon_m4',     
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_scar')] = {
        ['WeaponID'] = 'weapon_scar',     
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_groza')] = {
        ['WeaponID'] = 'weapon_groza',    
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_m70')] = {
        ['WeaponID'] = 'weapon_m70',    
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('WEAPON_HK416')] = {
        ['WeaponID'] = 'WEAPON_HK416',   
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_M6IC')] = {
        ['WeaponID'] = 'weapon_M6IC',   
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_G36A2')] = {
        ['WeaponID'] = 'weapon_G36A2',   
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_remington')] = {
        ['WeaponID'] = 'weapon_remington',   
        ['AmmoType'] = 'AMMO_SHOTGUN',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 24,
    },
    [GetHashKey('weapon_m1014')] = {
        ['WeaponID'] = 'weapon_m1014',   
        ['AmmoType'] = 'AMMO_SHOTGUN',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 24,
    },
    [GetHashKey('weapon_rubberslug')] = {
        ['WeaponID'] = 'weapon_rubberslug',   
        ['AmmoType'] = 'AMMO_RUBBER_SHOTGUN',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 20,
    },
    [GetHashKey('weapon_sniperrifle2')] = {
        ['WeaponID'] = 'weapon_sniperrifle2',   
        ['AmmoType'] = 'AMMO_SNIPER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 12,
    },
    [GetHashKey('weapon_huntrifle')] = {
        ['WeaponID'] = 'weapon_huntrifle',   
        ['AmmoType'] = 'AMMO_SNIPER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 15,
    },
    [GetHashKey('weapon_marksmanrifle')] = {
        ['WeaponID'] = 'weapon_marksmanrifle',   
        ['AmmoType'] = 'AMMO_SNIPER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 15,
    },
    [GetHashKey('weapon_empgun')] = {
        ['WeaponID'] = 'weapon_empgun',  
        ['AmmoType'] = 'AMMO_EMP',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 5,
    },
    -- Weapon : Melee
    [GetHashKey('weapon_flashlight')] = {
        ['WeaponID'] = 'weapon_flashlight',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.4,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_switchblade')] = {
        ['WeaponID'] = 'weapon_switchblade',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_gavel')] = {
        ['WeaponID'] = 'weapon_gavel',
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_shiv')] = {
        ['WeaponID'] = 'weapon_shiv',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_shoe')] = {
        ['WeaponID'] = 'weapon_shoe',
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.01,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_sledgeham')] = {
        ['WeaponID'] = 'weapon_sledgeham',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_nightstick')] = {
        ['WeaponID'] = 'weapon_nightstick',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_hammer')] = {
        ['WeaponID'] = 'weapon_hammer',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_knife')] = {
        ['WeaponID'] = 'weapon_knife',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_hatchet')] = {
        ['WeaponID'] = 'weapon_hatchet',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_wrench')] = {
        ['WeaponID'] = 'weapon_wrench',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_machete')] = {
        ['WeaponID'] = 'weapon_machete',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_bottle')] = {
        ['WeaponID'] = 'weapon_bottle',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_bat')] = {
        ['WeaponID'] = 'weapon_bat',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_knuckle')] = {
        ['WeaponID'] = 'weapon_knuckle',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.25,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_katana')] = {
        ['WeaponID'] = 'weapon_katana',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_crutch')] = {
        ['WeaponID'] = 'weapon_crutch',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_unicorn')] = {
        ['WeaponID'] = 'weapon_unicorn',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.1,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_unarmed')] = {
        ['WeaponID'] = 'weapon_unarmed',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    -- Weapon : Explosive
    [GetHashKey('weapon_grenade')] = {
        ['WeaponID'] = 'weapon_grenade',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_stickybomb')] = {
        ['WeaponID'] = 'weapon_stickybomb',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_smokegrenade')] = {
        ['WeaponID'] = 'weapon_stickybomb',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_flare')] = {
        ['WeaponID'] = 'weapon_flare',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_molotov')] = {
        ['WeaponID'] = 'weapon_molotov',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
}

--[[
    Icon Types:
    Car
    Motorcycle
    Truck
    Bicycle
    Van
]]

Shared.Vehicles = {
    -- Cycle
    [GetHashKey('bmx')] = {
        ['Vehicle'] = 'bmx',
        ['Model'] = 'Pedal',
        ['Name'] = 'BMX',
        ['ShopClass'] = 'Cycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Bicycle',
        ['Price'] = 450,
        ['CanBoost'] = false,
    },
    -- Compacts
    [GetHashKey('asbo')] = {
        ['Vehicle'] = 'asbo',
        ['Model'] = 'Maxwell',
        ['Name'] = 'Asbo',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36550,
        ['CanBoost'] = true,
    },
    -- Motorcycles
    [GetHashKey('bati')] = {
        ['Vehicle'] = 'bati',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Bati 801',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 35000,
        ['CanBoost'] = true,
    },
    [GetHashKey('sanchez')] = {
        ['Vehicle'] = 'sanchez',
        ['Model'] = 'Maibatsu',
        ['Name'] = 'Sanchez',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 45000,
        ['CanBoost'] = true,
    },
    [GetHashKey('faggio')] = {
        ['Vehicle'] = 'faggio',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Faggio Sport',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 5500,
        ['CanBoost'] = false,
    },
    -- Muscle
    [GetHashKey('dominator')] = {
        ['Vehicle'] = 'dominator',
        ['Model'] = 'Vapid',
        ['Name'] = 'Dominator',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 42500,
        ['CanBoost'] = true,
    },
    [GetHashKey('faction')] = {
        ['Vehicle'] = 'faction',
        ['Model'] = 'Willard',
        ['Name'] = 'Faction',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36500,
        ['CanBoost'] = true,
    },
    [GetHashKey('slamvan')] = {
        ['Vehicle'] = 'slamvan',
        ['Model'] = 'Vapid',
        ['Name'] = 'Slamvan',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 47500,
        ['CanBoost'] = false,
    },
    -- Sedans
    [GetHashKey('stratum')] = {
        ['Vehicle'] = 'stratum',
        ['Model'] = 'Zirconium',
        ['Name'] = 'Stratum',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 46550,
        ['CanBoost'] = true,
    },
    -- Sports
    [GetHashKey('banshee')] = {
        ['Vehicle'] = 'banshee',
        ['Model'] = 'Bravado',
        ['Name'] = 'Banshee',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 90000,
        ['CanBoost'] = true,
    },
    [GetHashKey('kuruma')] = {
        ['Vehicle'] = 'kuruma',
        ['Model'] = 'Karin',
        ['Name'] = 'Kuruma',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95000,
        ['CanBoost'] = true,
    },
    [GetHashKey('jugular')] = {
        ['Vehicle'] = 'jugular',
        ['Model'] = 'Ocelot',
        ['Name'] = 'Jugular',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 90000,
        ['CanBoost'] = true,
    },
    [GetHashKey('komoda')] = {
        ['Vehicle'] = 'komoda',
        ['Model'] = 'Lampadati',
        ['Name'] = 'Komoda',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 100000,
        ['CanBoost'] = true,
    },
    [GetHashKey('schafter3')] = {
        ['Vehicle'] = 'schafter3',
        ['Model'] = 'Benefactor',
        ['Name'] = 'Schafter V12',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95500,
        ['CanBoost'] = true,
    },
    [GetHashKey('sultan')] = {
        ['Vehicle'] = 'sultan',
        ['Model'] = 'Karin',
        ['Name'] = 'Sultan',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 92500,
        ['CanBoost'] = true,
    },
    [GetHashKey('sultan2')] = {
        ['Vehicle'] = 'sultan2',
        ['Model'] = 'Karin',
        ['Name'] = 'Sultan Sports',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95500,
        ['CanBoost'] = true,
    },
    -- Coupes
    [GetHashKey('f620')] = {
        ['Vehicle'] = 'f620',
        ['Model'] = 'Ocelot',
        ['Name'] = 'F620',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 75500,
        ['CanBoost'] = true,
    },
    [GetHashKey('oracle')] = {
        ['Vehicle'] = 'oracle',
        ['Model'] = 'Übermacht',
        ['Name'] = 'Oracle',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 84500,
        ['CanBoost'] = true,
    },
    -- Vans
    [GetHashKey('gburrito')] = {
        ['Vehicle'] = 'gburrito',
        ['Model'] = 'Declasse',
        ['Name'] = 'Burrito Mod',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 47550,
        ['CanBoost'] = false,
    },
    [GetHashKey('rumpo')] = {
        ['Vehicle'] = 'rumpo',
        ['Model'] = 'Bravado',
        ['Name'] = 'Rumpo',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 46440,
        ['CanBoost'] = false,
    },
    -- Custom
    [GetHashKey('gtr')] = {
        ['Vehicle'] = 'gtr',
        ['Model'] = 'Nissan',
        ['Name'] = 'GTR',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 245000,
    },
    -- POLICE
    [GetHashKey('polvic')] = {
        ['Vehicle'] = 'polvic',
        ['Model'] = 'Ford',
        ['Name'] = 'Crownvic',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polchal')] = {
        ['Vehicle'] = 'polchal',
        ['Model'] = 'Dodge',
        ['Name'] = 'Challenger',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polstang')] = {
        ['Vehicle'] = 'polstang',
        ['Model'] = 'Ford',
        ['Name'] = 'Mustang',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polvette')] = {
        ['Vehicle'] = 'polvette',
        ['Model'] = 'Chevrolet',
        ['Name'] = 'Corvette',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polexp')] = {
        ['Vehicle'] = 'polexp',
        ['Model'] = 'Ford',
        ['Name'] = 'Explorer',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polchar')] = {
        ['Vehicle'] = 'polchar',
        ['Model'] = 'Dodge',
        ['Name'] = 'Charger',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('polbike')] = {
        ['Vehicle'] = 'polbike',
        ['Model'] = 'Nagasaki',
        ['Name'] = 'PD Crosser',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Siren'] = 'RESIDENT_VEHICLES_SIREN_WAIL_03',
        ['Price'] = 1,
    },
    -- POLICE HELI
    [GetHashKey('airone')] = {
        ['Vehicle'] = 'airone',
        ['Model'] = '',
        ['Name'] = 'airone',
        ['ShopClass'] = 'Police',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Helicopter',
        ['Siren'] = '',
    },
    -- POLICE UC
    [GetHashKey('ucbanshee')] = {
        ['Vehicle'] = 'ucbanshee',
        ['Model'] = 'Bravado',
        ['Name'] = 'Banshee UC',
        ['ShopClass'] = '',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('ucrancher')] = {
        ['Vehicle'] = 'ucrancher',
        ['Model'] = 'Declasse',
        ['Name'] = 'Rancher UC',
        ['ShopClass'] = '',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('ucbuffalo')] = {
        ['Vehicle'] = 'ucbuffalo',
        ['Model'] = 'Bravado',
        ['Name'] = 'Buffalo UC',
        ['ShopClass'] = '',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('ucballer')] = {
        ['Vehicle'] = 'ucballer',
        ['Model'] = 'Gallivanter',
        ['Name'] = 'Baller UC',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    -- EMS
    [GetHashKey('emsspeedo')] = {
        ['Vehicle'] = 'emsspeedo',
        ['Model'] = 'Vapid',
        ['Name'] = 'Speedo',
        ['ShopClass'] = 'EMS',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'RESIDENT_VEHICLES_SIREN_WAIL_01'
    },
    [GetHashKey('airtwo')] = {
        ['Vehicle'] = 'airtwo',
        ['Model'] = '',
        ['Name'] = 'Air Two',
        ['ShopClass'] = 'EMS',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Helicopter',
        ['Siren'] = ''
    },
    -- JOB VEHS
    [GetHashKey('taxi')] = {
        ['Vehicle'] = 'taxi',
        ['Model'] = 'Vapid',
        ['Name'] = 'Taxi',
        ['ShopClass'] = 'Job',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 29500,
    },

    --ExtraVehiclesNames
    [GetHashKey('r8h')] = {
        ['Vehicle'] = 'r8h',
        ['Model'] = 'Audi',
        ['Name'] = 'R8 Hycade',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 299500,
    },
    [GetHashKey('veyronbb')] = {
        ['Vehicle'] = 'veyronbb',
        ['Model'] = 'Buggati',
        ['Name'] = 'Veyron Super Sport',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 2000000,
    },
    [GetHashKey('745le')] = {
        ['Vehicle'] = '745le',
        ['Model'] = 'BMW',
        ['Name'] = '745Le xDrive',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 200000,
    },
    [GetHashKey('a82020')] = {
        ['Vehicle'] = 'a82020',
        ['Model'] = 'Audi',
        ['Name'] = 'A8 2020',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 223000,
     },
     [GetHashKey('vwscirocco')] = {
        ['Vehicle'] = 'vwscirocco',
        ['Model'] = 'Volkswagen',
        ['Name'] = 'Scirocco 2.0TDI',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 223000,
     },
     [GetHashKey('mercml63')] = {
        ['Vehicle'] = 'mercml63',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'Brabus ML V12',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 400000,
     },
     [GetHashKey('ToraCullinanWB')] = {
        ['Vehicle'] = 'ToraCullinanWB',
        ['Model'] = 'Rolls-Royce',
        ['Name'] = 'Cullinan WideBody',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 600000,
     },
     [GetHashKey('w115200d')] = {
        ['Vehicle'] = 'w115200d',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'W115 200d',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 150000,
     },
     [GetHashKey('rev')] = {
        ['Vehicle'] = 'rev',
        ['Model'] = 'Lamborghini',
        ['Name'] = 'Countach LPI800-4',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 3000000,
    },
    [GetHashKey('mteche39')] = {
        ['Vehicle'] = 'mteche39',
        ['Model'] = 'BMW',
        ['Name'] = 'Mtech E39 530D',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('18mh5')] = {
        ['Vehicle'] = '18mh5',
        ['Model'] = 'BMW',
        ['Name'] = 'MH5 MANHART 2018',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 210000,
     },
     [GetHashKey('e60')] = {
        ['Vehicle'] = 'e60',
        ['Model'] = 'BMW',
        ['Name'] = 'E60 M5',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 150000,
     },
     [GetHashKey('tenf2')] = {
        ['Vehicle'] = 'tenf2',
        ['Model'] = 'Audi',
        ['Name'] = '10F WideBody',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 250000,
     },
     [GetHashKey('maj350z')] = {
        ['Vehicle'] = 'maj350z',
        ['Model'] = 'Nissan',
        ['Name'] = '350z',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 220000,
     },
     [GetHashKey('s30')] = {
        ['Vehicle'] = 's30',
        ['Model'] = 'Nissan',
        ['Name'] = 'Nissan fairladyz',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('r32')] = {
        ['Vehicle'] = 'r32',
        ['Model'] = 'Nissan',
        ['Name'] = 'GTR R-32',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('m2f22')] = {
        ['Vehicle'] = 'm2f22',
        ['Model'] = 'BMW',
        ['Name'] = 'M2 F-22',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('m3e30')] = {
        ['Vehicle'] = 'm3e30',
        ['Model'] = 'BMW',
        ['Name'] = 'M3 E30',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('22m5')] = {
        ['Vehicle'] = '22m5',
        ['Model'] = 'BMW',
        ['Name'] = 'M5 2022',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('m4')] = {
        ['Vehicle'] = 'm4',
        ['Model'] = 'Bmw',
        ['Name'] = 'M4-packet',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('gt63')] = {
        ['Vehicle'] = 'gt63',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'GT-63 AMG',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('a45amg')] = {
        ['Vehicle'] = 'a45amg',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'A45 AMG',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('mbc63')] = {
        ['Vehicle'] = 'mbc63',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'C-63 AMG',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('22g63')] = {
        ['Vehicle'] = '22g63',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'G-Class 63',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('gtrc')] = {
        ['Vehicle'] = 'gtrc',
        ['Model'] = 'Mercedes-Benz',
        ['Name'] = 'GTR-C AMG',
        ['ShopClass'] = '',
        ['Class'] = 'A',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('fnf4r34')] = {
        ['Vehicle'] = 'fnf4r34',
        ['Model'] = 'Nissan',
        ['Name'] = 'GTR R34',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('s15rb')] = {
        ['Vehicle'] = 's15rb',
        ['Model'] = 'Nissan',
        ['Name'] = 'Silva S15',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('audirs6tk')] = {
        ['Vehicle'] = 'audirs6tk',
        ['Model'] = 'Audi',
        ['Name'] = 'RS6 Custom',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('audirs6tk')] = {
        ['Vehicle'] = 'audirs6tk',
        ['Model'] = 'Audi',
        ['Name'] = 'RS6 Custom',
        ['ShopClass'] = '',
        ['Class'] = 'S',       
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 120000,
     },
     [GetHashKey('rr14')] = {
        ['Vehicle'] = 'rr14',
        ['Model'] = 'Range Rover',
        ['Name'] = 'Evoque',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 230000,
    },
    [GetHashKey('evo9')] = {
        ['Vehicle'] = 'evo9',
        ['Model'] = 'Mitsubishi',
        ['Name'] = 'Lancer Evo',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('a80')] = {
        ['Vehicle'] = 'a80',
        ['Model'] = 'Toyota',
        ['Name'] = 'A80 Supra',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 195000,
    },
    [GetHashKey('m3e30')] = {
        ['Vehicle'] = 'm3e30',
        ['Model'] = 'BMW',
        ['Name'] = 'M3 E30',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 195000,
    },
    [GetHashKey('subwrx')] = {
        ['Vehicle'] = 'subwrx',
        ['Model'] = 'Subaru',
        ['Name'] = 'Impreza WRX',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('jes')] = {
        ['Vehicle'] = 'jes',
        ['Model'] = 'Koenigsegg',
        ['Name'] = 'Jesko',
        ['ShopClass'] = '',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('m6f13')] = {
        ['Vehicle'] = 'm6f13',
        ['Model'] = 'BMW',
        ['Name'] = 'M6-F13',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('22b')] = {
        ['Vehicle'] = '22b',
        ['Model'] = 'Subaru',
        ['Name'] = 'Impreza 22B-STi',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 175000,
    },
    

    
    --ExtraCopCars--
    [GetHashKey('sjcop1')] = {
        ['Vehicle'] = 'sjcop1',
        ['Model'] = 'Dodge',
        ['Name'] = 'Hellcat Charger',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 150000,
    },
    [GetHashKey('expedition')] = {
        ['Vehicle'] = 'expedition',
        ['Model'] = 'Ford',
        ['Name'] = 'Expedition',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100,
    },
    [GetHashKey('m3g80umnon')] = {
        ['Vehicle'] = 'm3g80umnon',
        ['Model'] = 'BMW',
        ['Name'] = 'M3G80 Undercover',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('M5RB_VV')] = {
        ['Vehicle'] = 'M5RB_VV',
        ['Model'] = 'BMW',
        ['Name'] = 'M5 Undercover',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('mrkoctavia')] = {
        ['Vehicle'] = 'mrkoctavia',
        ['Model'] = 'Skoda',
        ['Name'] = 'Octavia',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('charger19')] = {
        ['Vehicle'] = 'charger19',
        ['Model'] = 'Mustang',
        ['Name'] = 'Charger Police',
        ['ShopClass'] = '',
        ['Class'] = 'S+',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
    [GetHashKey('riot')] = {
        ['Vehicle'] = 'riot',
        ['Model'] = 'SWAT',
        ['Name'] = 'Truck',
        ['ShopClass'] = '',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 5,
    },
    [GetHashKey('22530i')] = {
        ['Vehicle'] = '22530i',
        ['Model'] = 'BMW',
        ['Name'] = '530i Police',
        ['ShopClass'] = '',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 1,
    },
}

Shared.VehicleColors = {
    [1] = "Metallic Graphite Black",[2] = "Metallic Black Steel",[3] = "Metallic Dark Silver",[4] = "Metallic Silver",[5] = "Metallic Blue Silver",[6] = "Metallic Steel Gray",[7] = "Metallic Shadow Silver",[8] = "Metallic Stone Silver",[9] = "Metallic Midnight Silver",[10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",[12] = "Matte Black",[13] = "Matte Gray",[14] = "Matte Light Grey",[15] = "Util Black",[16] = "Util Black Poly",[17] = "Util Dark silver",[18] = "Util Silver",[19] = "Util Gun Metal",[20] = "Util Shadow Silver",
    [21] = "Worn Black",[22] = "Worn Graphite",[23] = "Worn Silver Grey",[24] = "Worn Silver",[25] = "Worn Blue Silver",[26] = "Worn Shadow Silver",[27] = "Metallic Red",[28] = "Metallic Torino Red",[29] = "Metallic Formula Red",[30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",[32] = "Metallic Garnet Red",[33] = "Metallic Desert Red",[34] = "Metallic Cabernet Red",[35] = "Metallic Candy Red",[36] = "Metallic Sunrise Orange",[37] = "Metallic Classic Gold",[38] = "Metallic Orange",[39] = "Matte Red",[40] = "Matte Dark Red",
    [41] = "Matte Orange",[42] = "Matte Yellow",[43] = "Util Red",[44] = "Util Bright Red",[45] = "Util Garnet Red",[46] = "Worn Red",[47] = "Worn Golden Red",[48] = "Worn Dark Red",[49] = "Metallic Dark Green",[50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",[52] = "Metallic Olive Green",[53] = "Metallic Green",[54] = "Metallic Gasoline Blue Green",[55] = "Matte Lime Green",[56] = "Util Dark Green",[57] = "Util Green",[58] = "Worn Dark Green",[59] = "Worn Green",[60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",[62] = "Metallic Dark Blue",[63] = "Metallic Saxony Blue",[64] = "Metallic Blue",[65] = "Metallic Mariner Blue",[66] = "Metallic Harbor Blue",[67] = "Metallic Diamond Blue",[68] = "Metallic Surf Blue",[69] = "Metallic Nautical Blue",[70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",[72] = "Metallic Spinnaker Blue",[73] = "Metallic Ultra Blue",[74] = "Metallic Bright Blue",[75] = "Util Dark Blue",[76] = "Util Midnight Blue",[77] = "Util Blue",[78] = "Util Sea Foam Blue",[79] = "Uil Lightning blue",[80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",[82] = "Matte Dark Blue",[83] = "Matte Blue",[84] = "Matte Midnight Blue",[85] = "Worn Dark blue",[86] = "Worn Blue",[87] = "Worn Light blue",[88] = "Metallic Taxi Yellow",[89] = "Metallic Race Yellow",[90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",[92] = "Metallic Lime",[93] = "Metallic Champagne",[94] = "Metallic Pueblo Beige",[95] = "Metallic Dark Ivory",[96] = "Metallic Choco Brown",[97] = "Metallic Golden Brown",[98] = "Metallic Light Brown",[99] = "Metallic Straw Beige",[100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",[102] = "Metallic Beechwood",[103] = "Metallic Dark Beechwood",[104] = "Metallic Choco Orange",[105] = "Metallic Beach Sand",[106] = "Metallic Sun Bleeched Sand",[107] = "Metallic Cream",[108] = "Util Brown",[109] = "Util Medium Brown",[110] = "Util Light Brown",
    [111] = "Metallic White",[112] = "Metallic Frost White",[113] = "Worn Honey Beige",[114] = "Worn Brown",[115] = "Worn Dark Brown",[116] = "Worn straw beige",[117] = "Brushed Steel",[118] = "Brushed Black steel",[119] = "Brushed Aluminium",[120] = "Chrome",
    [121] = "Worn Off White",[122] = "Util Off White",[123] = "Worn Orange",[124] = "Worn Light Orange",[125] = "Metallic Securicor Green",[126] = "Worn Taxi Yellow",[127] = "police car blue",[128] = "Matte Green",[129] = "Matte Brown",[130] = "Worn Orange",
    [131] = "Matte White",[132] = "Worn White",[133] = "Worn Olive Army Green",[134] = "Pure White",[135] = "Hot Pink",[136] = "Salmon pink",[137] = "Metallic Vermillion Pink",[138] = "Orange",[139] = "Green",[140] = "Blue",
    [141] = "Mettalic Black Blue",[142] = "Metallic Black Purple",[143] = "Metallic Black Red",[144] = "hunter green",[145] = "Metallic Purple",[146] = "Metaillic V Dark Blue",[147] = "MODSHOP BLACK1",[148] = "Matte Purple",[149] = "Matte Dark Purple",[150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",[152] = "Matte Olive Drab",[153] = "Matte Desert Brown",[154] = "Matte Desert Tan",[155] = "Matte Foilage Green",[156] = "DEFAULT ALLOY COLOR",[157] = "Epsilon Blue",[158] = "Unknown",
}